### ISSUE TITLE
test_BBAD_I fails when running in octave (error: imgradientxy: IMG must be a gray-scale image)

### ISSUE THREAD

**Issue by nickossaf** [google/bband-adaband#1]
Hi, running test_BBAD_I.m from octave, there is an error:

error: imgradientxy: IMG must be a gray-scale image
error: called from
    imgradientxy at line 58 column 5
    imgradient at line 46 column 20
    BBAD_I>get_si at line 278 column 10
    BBAD_I at line 240 column 6
    test_BBAD_I>run_test_case at line 28 column 71
    test_BBAD_I at line 19 column 1

**Comment by vztu** [comment]
Hi Nick, I ran test_BBAD_I.m in MATLAB2020 and got correct results:
```
>> addpath(genpath('../'))
>> test_BBAD_I
sky2_1s_trans_248_1920x1080: pass
Elapsed time is 5.363147 seconds.
plant1_1s_trans_248_1920x1080: pass
Elapsed time is 1.691918 seconds.
```
It seems MATLAB's built-in function `imgradient()` was different from Octave from the error log. I am sorry that I am not familiar with Octave, so it is recommended that you use this code in MATLAB.

**Comment by nbirkbeck** [comment]
It seems like octave's version of imgradient is expecting input to be uint8 (not double). With this small change:
```
[mag, ~] = imgradient(uint8(Y));
```
test_BBAD_I will pass but there are still other missing pieces for the debanding filter (and the runtime in octave is poor, note runtimes below).

```
octave:14> test_BBAD_I
sky2_1s_trans_248_1920x1080: pass
Elapsed time is 166.894 seconds.
plant1_1s_trans_248_1920x1080: pass
Elapsed time is 100.27 seconds.
```

**Comment by nbirkbeck** [comment]
Given that BBAD_I only uses ```get_SI``` on im_Y which is already cast to uint8 here:
https://github.com/google/bband-adaband/blob/a896f7336387e1e004dbbb7bc7c3028db1769c54/src/BBAD_I.m#L80

And that ```imgradient``` returns the same result regardless of whether the input is uint8 or double (tests pass). I've submitted the patch:
https://github.com/google/bband-adaband/commit/a896f7336387e1e004dbbb7bc7c3028db1769c54
which should fix this issue.
